version: '3'
services:
  node:
    build:
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./app:/home/nodejs
